# Generated by Django 5.1.6 on 2025-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bolsillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsillo',
            name='meta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bolsillo',
            name='tipo',
            field=models.CharField(choices=[('AHORRO', 'Ahorro'), ('GASTOS', 'Gastos'), ('INVERSION', 'Inversión'), ('OTRO', 'Otro')], default='AHORRO', max_length=10),
        ),
        migrations.AlterField(
            model_name='bolsillo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
