# Generated by Django 5.1.6 on 2025-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comisiones', models.CharField(max_length=100)),
                ('requisitos', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
