"""
Django settings for smartwallet project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', '0207')  # Cambia esto en producción
DEBUG = os.environ.get('DEBUG', 'False') == 'True'


ALLOWED_HOSTS = [
    'smartwallet-tc25.onrender.com', 
    'localhost',  
    '127.0.0.1',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

WSGI_APPLICATION = 'smartwallet.wsgi.application'

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://smartwalletdb_user:sAiVLJruw0IEEt5ZPzzSXCwhTp8ZNb4m@dpg-d0e0su15pdvs73aksfhg-a.oregon-postgres.render.com/smartwalletdb',
        conn_max_age=600,
        ssl_require=True
    )
}


DATABASES = {    
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bufhoonj2qiypujpk7yp',  
        'USER': 'uhzypnqfsumppely',      
        'PASSWORD': '8HsLr6QsZu3cgVQymjsV',  
        'HOST': 'bufhoonj2qiypujpk7yp-mysql.services.clever-cloud.com',  
        'PORT': '3306',                  
        'OPTIONS': {
            'charset': 'utf8mb4',        
            'ssl_mode': 'DISABLED'      
        }
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  
CACHES = {
    "http://127.0.0.1:8000",
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Configuración de cookies y HTTPS (obligatorio en Render)
CSRF_COOKIE_SECURE = True  # Solo enviar CSRF sobre HTTPS
SESSION_COOKIE_SECURE = True  # Solo enviar sesiones sobre HTTPS
SECURE_SSL_REDIRECT = True  # Redirigir HTTP a HTTPS (Render lo maneja)

CORS_ALLOWED_ORIGINS = [
    "https://smartwallet-tc25.onrender.com/",
    "http://localhost:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://smartwallet-tc25.onrender.com/",
]

CORS_ALLOW_CREDENTIALS = True

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
